-- Generated by drizzle-kit. KEEP THIS IDEMPOTENT: migrations run on every
-- container start (see ../Dockerfile), so a statement that fails on re-run
-- crash-loops the API. drizzle-kit already emits CREATE TABLE/INDEX IF NOT
-- EXISTS and wraps ALTER TABLE ... ADD CONSTRAINT in a
-- DO $$ ... EXCEPTION WHEN duplicate_object $$ guard; if you hand-edit or add
-- statements here, match that pattern (ADD COLUMN IF NOT EXISTS, etc).
CREATE TABLE IF NOT EXISTS "announcements" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"event_id" uuid NOT NULL,
	"subject" text NOT NULL,
	"body" text NOT NULL,
	"audience" text DEFAULT 'all' NOT NULL,
	"recipient_count" integer DEFAULT 0 NOT NULL,
	"sent_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "announcements_audience_check" CHECK ("announcements"."audience" in ('all','attending','pending','maybe','declined'))
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "event_templates" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"key" text NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"category" text DEFAULT 'general' NOT NULL,
	"theme" jsonb NOT NULL,
	"preview_image_key" text,
	"is_system" boolean DEFAULT true NOT NULL,
	"created_by" uuid,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "event_templates_key_unique" UNIQUE("key"),
	CONSTRAINT "event_templates_ownership_check" CHECK (("event_templates"."is_system" and "event_templates"."created_by" is null) or (not "event_templates"."is_system" and "event_templates"."created_by" is not null))
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "event_views" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"event_id" uuid NOT NULL,
	"guest_id" uuid,
	"visitor_hash" text NOT NULL,
	"viewed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"viewed_hour" timestamp with time zone NOT NULL,
	CONSTRAINT "uq_event_views_hourly" UNIQUE("event_id","visitor_hash","viewed_hour")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"host_id" uuid NOT NULL,
	"slug" text DEFAULT gen_random_uuid()::text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"host_display_name" text,
	"starts_at" timestamp with time zone NOT NULL,
	"ends_at" timestamp with time zone,
	"timezone" text DEFAULT 'UTC' NOT NULL,
	"location_name" text,
	"location_address" text,
	"location_map_url" text,
	"cover_image_key" text,
	"template_id" uuid,
	"theme_overrides" jsonb,
	"status" text DEFAULT 'draft' NOT NULL,
	"rsvp_deadline" timestamp with time zone,
	"allow_plus_ones" boolean DEFAULT true NOT NULL,
	"max_plus_ones" integer DEFAULT 2 NOT NULL,
	"capacity" integer,
	"collect_dietary" boolean DEFAULT false NOT NULL,
	"allow_public_rsvp" boolean DEFAULT true NOT NULL,
	"guestbook_enabled" boolean DEFAULT true NOT NULL,
	"guest_photos_enabled" boolean DEFAULT true NOT NULL,
	"show_guest_list" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "events_slug_unique" UNIQUE("slug"),
	CONSTRAINT "events_status_check" CHECK ("events"."status" in ('draft','published','cancelled','archived')),
	CONSTRAINT "events_slug_length_check" CHECK (length("events"."slug") >= 12),
	CONSTRAINT "events_max_plus_ones_check" CHECK ("events"."max_plus_ones" >= 0),
	CONSTRAINT "events_capacity_check" CHECK ("events"."capacity" is null or "events"."capacity" > 0),
	CONSTRAINT "events_ends_after_starts_check" CHECK ("events"."ends_at" is null or "events"."ends_at" >= "events"."starts_at")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "guestbook_posts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"event_id" uuid NOT NULL,
	"guest_id" uuid,
	"author_name" text NOT NULL,
	"body" text,
	"image_key" text,
	"status" text DEFAULT 'visible' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "guestbook_posts_status_check" CHECK ("guestbook_posts"."status" in ('visible','hidden')),
	CONSTRAINT "guestbook_posts_content_check" CHECK ("guestbook_posts"."body" is not null or "guestbook_posts"."image_key" is not null)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "guests" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"event_id" uuid NOT NULL,
	"invite_token" uuid DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"email" text,
	"phone" text,
	"rsvp_status" text DEFAULT 'pending' NOT NULL,
	"plus_ones" integer DEFAULT 0 NOT NULL,
	"dietary_notes" text,
	"message" text,
	"source" text DEFAULT 'invited' NOT NULL,
	"invited_at" timestamp with time zone,
	"first_viewed_at" timestamp with time zone,
	"last_viewed_at" timestamp with time zone,
	"responded_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "guests_invite_token_unique" UNIQUE("invite_token"),
	CONSTRAINT "guests_rsvp_status_check" CHECK ("guests"."rsvp_status" in ('pending','attending','declined','maybe')),
	CONSTRAINT "guests_source_check" CHECK ("guests"."source" in ('invited','public')),
	CONSTRAINT "guests_plus_ones_check" CHECK ("guests"."plus_ones" >= 0)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "rsvp_log" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"guest_id" uuid NOT NULL,
	"event_id" uuid NOT NULL,
	"previous_status" text,
	"new_status" text NOT NULL,
	"plus_ones" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "sessions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"refresh_token_hash" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" text NOT NULL,
	"password_hash" text NOT NULL,
	"display_name" text,
	"role" text DEFAULT 'host' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email"),
	CONSTRAINT "users_role_check" CHECK ("users"."role" in ('host','admin'))
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "announcements" ADD CONSTRAINT "announcements_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "event_templates" ADD CONSTRAINT "event_templates_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "event_views" ADD CONSTRAINT "event_views_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "event_views" ADD CONSTRAINT "event_views_guest_id_guests_id_fk" FOREIGN KEY ("guest_id") REFERENCES "public"."guests"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "events" ADD CONSTRAINT "events_host_id_users_id_fk" FOREIGN KEY ("host_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "events" ADD CONSTRAINT "events_template_id_event_templates_id_fk" FOREIGN KEY ("template_id") REFERENCES "public"."event_templates"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "guestbook_posts" ADD CONSTRAINT "guestbook_posts_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "guestbook_posts" ADD CONSTRAINT "guestbook_posts_guest_id_guests_id_fk" FOREIGN KEY ("guest_id") REFERENCES "public"."guests"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "guests" ADD CONSTRAINT "guests_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "rsvp_log" ADD CONSTRAINT "rsvp_log_guest_id_guests_id_fk" FOREIGN KEY ("guest_id") REFERENCES "public"."guests"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "rsvp_log" ADD CONSTRAINT "rsvp_log_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_announcements_event" ON "announcements" USING btree ("event_id","created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_event_templates_created_by" ON "event_templates" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_event_views_event" ON "event_views" USING btree ("event_id","viewed_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_events_host" ON "events" USING btree ("host_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_events_starts_at" ON "events" USING btree ("starts_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_guestbook_event" ON "guestbook_posts" USING btree ("event_id","created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_guests_event" ON "guests" USING btree ("event_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_guests_event_status" ON "guests" USING btree ("event_id","rsvp_status");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_guests_event_email" ON "guests" USING btree ("event_id",lower("email")) WHERE "guests"."email" is not null;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_rsvp_log_event" ON "rsvp_log" USING btree ("event_id","created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_sessions_user" ON "sessions" USING btree ("user_id");